### ISSUE TITLE
完全无法使用

### ISSUE THREAD

**Issue by CaveNightingale** [Andy-K-Sparklight/EQLauncher#3]
1，已安装Java并且位于PATH环境变量中但仍显示未安装JAVA，尝试指定JAVA_HOME后依然报错
2，无法下载Minecraft，一直提示正在寻找此版本
3，请设置任务栏图标而不是使用默认的未知应用程序图标
4，点击按钮时左侧栏发生闪烁
5，此项目弃坑了吗？

**Comment by Andy-K-Sparklight** [comment]
本来写了一些，但发现Electron特性极多，因此准备转NW.js，受此影响，该项目可能无法继续维护。
